name: Renovate
on:
  push:
    paths:
      - '.github/workflows/renovate.yml'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run renovate
        run: npx -y renovate
        env:
          RENOVATE_CONFIG_FILE: renovate/config.js
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_REPOSITORIES: pujanshah3333/gradle-sample-app
          LOG_LEVEL: 'debug'
